
job:
  experiment_name: "auto-run-2"
  param_spec_file: "param_spec.yaml"
  sketch_dir: "/home/sjkro1/ARC-Discovery/Harmonograph" # insert user sketch path here
  prompt_filepath: "prompt.txt"
  population_size: 20
  processing: parallel
  screen: False
  workers: 8
  runs: 5




        
 